// Package autoscaler provides automatic cloud worker provisioning for Nagare.
//
// # Overview
//
// The autoscaler monitors queue depth per worker pool and automatically spins
// up cloud VM or container workers when demand exceeds local capacity.  It
// also tears workers down after they have been idle for a configurable period,
// keeping infrastructure costs proportional to actual load.
//
// # Architecture
//
//	Coordinator (master)
//	      │
//	      ▼
//	  Autoscaler ──── tick loop (every N seconds)
//	      │               │
//	      │      scale-up │ queue depth > threshold
//	      │               ▼
//	      │         CloudProvider.SpinUp()
//	      │               │
//	      │               ▼
//	      │         WorkerInstance (running)
//	      │               │
//	      │               ▼ registers via /api/workers/register
//	      └──────── Coordinator tracks as a normal remote worker
//	                      │
//	      scale-down       │ idle > threshold
//	      CloudProvider.SpinDown()
//
// # Provider Implementations
//
//   - DockerProvider: uses the local Docker daemon; ideal for development and
//     testing without real cloud credentials.
//   - AWSProvider: uses Amazon EC2 RunInstances / TerminateInstances.
//
// # Adding a New Provider
//
// Implement the CloudProvider interface defined in this file, register it in
// NewProvider, and add the corresponding configuration struct to
// internal/config.AutoscalerConfig.
package autoscaler

import (
	"context"
	"time"
)

// InstanceStatus represents the lifecycle state of a cloud-provisioned worker.
type InstanceStatus string

const (
	// InstanceProvisioning means the cloud API call has been made but the
	// instance is not yet reachable (booting, installing software, etc.).
	InstanceProvisioning InstanceStatus = "provisioning"

	// InstanceRunning means the instance is live and the nagare worker
	// process has registered with the master.
	InstanceRunning InstanceStatus = "running"

	// InstanceDraining means the autoscaler has decided to terminate this
	// instance but is waiting for in-flight tasks to complete.
	InstanceDraining InstanceStatus = "draining"

	// InstanceTerminated means the instance has been stopped and its cloud
	// resources have been released.
	InstanceTerminated InstanceStatus = "terminated"
)

// WorkerInstance describes a cloud-provisioned nagare worker.
type WorkerInstance struct {
	// ID is the Nagare-internal identifier, set at provisioning time.
	// Format: "<provider>-<random-suffix>" (e.g. "docker-a3f1b2").
	ID string

	// ProviderID is the cloud-specific identifier for the underlying
	// resource (e.g. an EC2 instance ID "i-0abc123", or a Docker container
	// ID).
	ProviderID string

	// WorkerID is the nagare cluster worker ID that the remote process
	// registers with after boot.  Empty until the worker has called
	// POST /api/workers/register.
	WorkerID string

	// Pools is the list of task queues this worker serves.
	Pools []string

	// InstanceType is the cloud provider's instance/machine type
	// (e.g. "t3.medium", "g4dn.xlarge").  Empty for Docker workers.
	InstanceType string

	// Region is the geographic region the instance was launched in.
	// Empty for Docker workers.
	Region string

	// Status is the current lifecycle state.
	Status InstanceStatus

	// CostPerHour is the estimated hourly cost in USD for this instance
	// type.  Zero when unknown.
	CostPerHour float64

	// CreatedAt is when Nagare asked the provider to create this instance.
	CreatedAt time.Time

	// TerminatedAt is when the instance was terminated.  Zero if still alive.
	TerminatedAt time.Time
}

// SpinUpRequest carries everything the CloudProvider needs to create a new
// worker instance and configure it to join the master.
type SpinUpRequest struct {
	// InstanceID is the Nagare-assigned ID that will be stamped onto the
	// resulting WorkerInstance.  Generated by the autoscaler before calling
	// SpinUp so that the ID is known before the API round-trip completes.
	InstanceID string

	// Pools is the list of task queues this worker should serve.
	Pools []string

	// MasterAddr is the full URL of the Nagare master
	// (e.g. "http://10.0.0.1:8080").  The spawned binary will be started
	// with --join <MasterAddr>.
	MasterAddr string

	// Token is the shared secret for master-worker authentication.
	// Passed as --token to the spawned worker process.
	Token string

	// NeedsGPU indicates the pool requires GPU resources.  Providers that
	// support multiple instance families (e.g. AWS) should select a GPU
	// instance type when this is true.
	NeedsGPU bool
}

// CloudProvider is the abstraction over a cloud or container backend that can
// create and destroy nagare worker instances on demand.
//
// Implementations must be safe for concurrent use.
type CloudProvider interface {
	// SpinUp creates a new worker instance and configures it to register
	// with the master specified in req.  The method must return as soon as
	// the underlying resource has been requested — it must NOT block until
	// the worker is fully booted.  The returned WorkerInstance will have
	// Status == InstanceProvisioning.
	SpinUp(ctx context.Context, req SpinUpRequest) (WorkerInstance, error)

	// SpinDown terminates the instance identified by providerID.  Callers
	// are responsible for ensuring in-flight tasks have been drained before
	// calling SpinDown; the provider performs a hard termination.
	SpinDown(ctx context.Context, providerID string) error

	// List returns all cloud-managed instances that are currently alive
	// (i.e. not yet terminated).  Used on master startup to reconcile any
	// instances left over from a previous run.
	List(ctx context.Context) ([]WorkerInstance, error)

	// Name returns the provider's identifier string (e.g. "docker", "aws").
	// Used for logging and in the cloud_instances table.
	Name() string
}

// PoolStats summarises current utilisation for a single worker pool.
// The autoscaler uses this to decide whether to scale up or down.
type PoolStats struct {
	// Pool is the pool name.
	Pool string

	// QueuedTasks is the number of tasks currently waiting to be picked up.
	QueuedTasks int

	// ActiveWorkers is the number of workers (local + cloud) currently
	// online for this pool.
	ActiveWorkers int

	// CloudWorkers is the subset of ActiveWorkers that were auto-provisioned.
	CloudWorkers int

	// NeedsGPU is true when at least one queued task in this pool has GPU
	// resource requirements.
	NeedsGPU bool
}
